spring:
  application:
    name: api-gateway
  profiles: default
    
server:
  port: 8888
  
management:
  endpoint:
    restart:
      enabled: true
    shutdown:
      enabled: true
    health:
      sensitive: false 
zuul:
  ignoredServices: "*"
  routes:
    group-service:  
      sensitiveHeaders:
      path: /gs/**
      serviceId: GROUPSERVICE
  host:
    socket-timeout-millis: 60000
    connect-timeout-millis: 60000      
      
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  server:
    wait-time-in-ms-when-sync-empty: 3000
    

ribbon:
  eureka:
    enabled: true
  ReadTimeout: 60000
  ConnectTimeout: 60000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000